CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_PRINTK=y

CONFIG_HEAP_MEM_POOL_SIZE=2048

# Enables the console driver
CONFIG_CONSOLE=y

# Directs printf/printk to the console driver
CONFIG_UART_CONSOLE=y

# Enables the UART driver for the ESP32
CONFIG_SERIAL=y

# Adds a 2-second delay at boot so you have time to connect your terminal
CONFIG_BOOT_BANNER=y